global:
  scrape_interval: 15s  # Частота сбора метрик

scrape_configs:
  - job_name: 'book-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['book-service:8080']

  - job_name: 'moderator-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['moderator-service:8080']