version: '3.8'

services:
  hw24:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hw24
    ports:
      - "8080:8080"
    networks:
      - monitoring1

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring1

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - monitoring1

networks:
  monitoring1:
    driver: bridge