server:
  port: ${SERVICE_PORT:8080}
  ssl:
    enabled: false
spring:
  application:
    name: book-service
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

  h2:
    console:
      path: /h2-console
  #      settings:
  #        web-allow-others: true
  liquibase:
    enabled: true
    change-log: classpath*:db/changelog/rootChangeLog.xml
  sql:
    init:
      mode: never

jwt:
  secret: top-secret

moderator-url: ${MODERATOR_SERVICE_URL:http://localhost:8081/moderator}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
        step: 1m

  endpoint:
    prometheus:
      enabled: true
    logfile:
      enabled: true
      external-file: ./logs/application.log
    metrics:
      enabled: true
    health:
      show-details: always

logging:
  file:
    name: ./logs/application.log
  level:
    root: ${LOGGING_ROOT_LEVEL:INFO}
    ru.otus.spring.book: ${LOGGING_LEVEL:INFO}

