spring:
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      path: /h2-console
#      settings:
#        web-allow-others: true
  liquibase:
    enabled: true
    change-log: classpath*:db/changelog/rootChangeLog.xml