server:
  port: ${SERVICE_PORT:8080}
spring:
  application:
    name: moderator-service
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

  h2:
    console:
      path: /h2-console
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/rootChangeLog.xml
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
        step: 1m

  endpoint:
    prometheus:
      enabled: true
    logfile:
      enabled: true
      external-file:  ./logs/application.log
    metrics:
      enabled: true
    health:
      show-details: always

logging:
  file:
    name:  ./logs/application.log
  level:
    root: ${LOGGING_ROOT_LEVEL:INFO}
    ru.otus.spring.moderator: ${LOGGING_LEVEL:INFO}
